# Generated by Django 5.0.6 on 2024-06-09 11:47

import aceshigh.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_yourmodel_code_yourmodel_description_yourmodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="yourmodel",
            name="markdown",
            field=aceshigh.fields.AceEditorField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yourmodel",
            name="test",
            field=aceshigh.fields.AceEditorField(default=""),
            preserve_default=False,
        ),
    ]
