# Generated by Django 5.0.6 on 2024-06-04 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aceshigh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="editormodeprofile",
            unique_together={("user", "mode")},
        ),
    ]
