# Generated by Django 5.0.6 on 2024-06-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aceshigh", "0003_alter_editormodeprofile_editor_css"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="editormodeprofile",
            unique_together=set(),
        ),
    ]
