# Generated by Django 5.0.6 on 2024-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aceshigh", "0004_alter_editormodeprofile_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editormodeprofile",
            name="editor_css",
            field=models.TextField(
                blank=True,
                default="#editor { \n        width: 100%; \n        height: 500px;\n    }\n    ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="editorprofile",
            name="default_editor_css",
            field=models.TextField(
                default="#editor { \n        width: 100%; \n        height: 500px;\n    }\n    "
            ),
        ),
    ]
