# Generated by Django 5.0.6 on 2024-06-04 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aceshigh", "0005_alter_editormodeprofile_editor_css_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="editormodeprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mode_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
