# Generated by Django 5.0.6 on 2024-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aceshigh", "0006_alter_editormodeprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editormodeprofile",
            name="editor_css",
            field=models.CharField(
                blank=True,
                default="width: 100%;  height: 500px;",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="editorprofile",
            name="default_editor_css",
            field=models.CharField(
                blank=True,
                default="width: 100%;  height: 500px;",
                max_length=200,
                null=True,
            ),
        ),
    ]
