# Generated by Django 5.0.6 on 2024-06-06 13:52

import aceshigh.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_mypage_homepage_content_homepage_css_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="markdown_content",
            field=aceshigh.fields.AceEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="python_content",
            field=aceshigh.fields.AceEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=aceshigh.fields.AceEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="css_content",
            field=aceshigh.fields.AceEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="js_content",
            field=aceshigh.fields.AceEditorField(blank=True, null=True),
        ),
    ]
